name: Next.js CI
on:
  pull request:
    branches: [main]

job:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install denpendency
        uses: npm lint

      - name: Check code formatting
        run: npm run format:check

      - name: Run lint
        run: npm run lint
